### ISSUE TITLE
There's no maven artifact for module `service` in mavenrepository.com, how can I import this dependency?

### ISSUE THREAD

**Issue by wqtang-sib** [TheoKanning/openai-java#103]
I can only find module `api` and `client` in mavenrepository.com

**Comment by TheoKanning** [comment]
It's showing up for me now, maybe it just took a little while to appear since I only created it yesterday. https://mvnrepository.com/artifact/com.theokanning.openai-gpt3-java

Are you using the latest version? The service library only exists in versions 0.10.0 and later

**Comment by wqtang-sib** [comment]
Thank you! 😄 I can see it now, with version 0.10.0
