### ISSUE TITLE
demo code return with error 400

### ISSUE THREAD

**Issue by CrocoRyan** [TheoKanning/openai-java#104]
I strictly followed the demo code, but still got http 400 error when i call it
![image](https://user-images.githubusercontent.com/29674755/218810694-7485c356-0434-450c-b067-4b4ebfcfa24e.png)
![image](https://user-images.githubusercontent.com/29674755/218810783-b4c31e7f-2697-4340-b28d-8e9898f09caa.png)

**Comment by zengwp** [comment]
OpenAiService service = new OpenAiService("xxxx",Duration.ofSeconds(300));
CompletionRequest completionRequest = CompletionRequest.builder()
	                .prompt("说出你的问题")
	                .model("text-davinci-003").maxTokens(2048)
	                .build();
System.out.println(service.createCompletion(completionRequest).getChoices().get(0).getText());

**Comment by CrocoRyan** [comment]
> Try upgrading to 0.10.0 and switching to the `OpenAiService` in the `service` library. It will give more detailed info when a request fails.
> 
> Does running the example work for you?

I've already done those in my project. I managed to invalidate cache & restart my ide, and now it works
