### ISSUE TITLE
Is there any way to remove the unnecessary line separator '\n' at the beginning of text in response?

### ISSUE THREAD

**Issue by wqtang-sib** [TheoKanning/openai-java#108]
![image](https://user-images.githubusercontent.com/107017459/219027780-8844551b-34e1-415f-9270-13ad3137eafe.png)

**Comment by nopalfi** [comment]
Does the output always start with "\n\n" if it does then you can just remove the first "\n\n" if it exists.
`if (text.startsWith("\\n\\n")) {
text = text.replace("\\n\\n", ""); // replace '\n\n' into blank
}`

or
`if (text.startsWith("\\n\\n")) {
text = text.substring(5); // take the string after index 4
}`

**Comment by cla52013** [comment]
replace("\n\n","\n")

**Comment by zengwp** [comment]
str=str.trim()

**Comment by wqtang-sib** [comment]
> Does the output always start with "\n\n" if it does then you can just remove the first "\n\n" if it exists.
> ```
> if (text.startsWith("\\n\\n")) {
> text = text.replace("\\n\\n", ""); // replace '\n\n' into blank
> }
> ```
> 
> or
> ```
> if (text.startsWith("\\n\\n")) {
> text = text.substring(5); // take the string after index 4
> }
> ```

Yes, it seems that every response text starts with '\n'.
Thanks for your helpful solutions!
