### ISSUE TITLE
为什么返回的Choices.text中经常有不相关内容

### ISSUE THREAD

**Issue by zengwp** [TheoKanning/openai-java#109]
![image](https://user-images.githubusercontent.com/35715948/219313559-3dae91e2-483b-4e0b-843f-5989deeec84f.png)

**Comment by mshen6666** [comment]
你试试用stringbuilder来接受，拼起来，我理解有可能是上下文之间的符号，我自己拼没有遇到过这个问题。你在使用中返回时间大概是多少啊，我一般都是十秒左右了

**Comment by zengwp** [comment]
> 你试试用stringbuilder来接受，拼起来，我理解有可能是上下文之间的符号，我自己拼没有遇到过这个问题。你在使用中返回时间大概是多少啊，我一般都是十秒左右了

截图就是返回的所以上下文了
我试了很久，不同的问题，返回的时间不同，最长的有一分多钟，比如一些文案类，构建答案之类

**Comment by mshen6666** [comment]
你有试过联系上下文吗，我看api目前没有好的方案

**Comment by zengwp** [comment]
> 你有试过联系上下文吗，我看api目前没有好的方案

大致可以通过两种方式实现
1、在提交的prompt中携带上下文，比如：问：xxx \n\n 答：xxx \n\n 问：xxx
此项可以在官方示例中看到
2、通过[Fine-tuning](https://platform.openai.com/docs/guides/fine-tuning/fine-tuning)实现，这个我没弄

**Comment by zengwp** [comment]
@TheoKanning  Please help me

**Comment by mshen6666** [comment]
好的谢谢

**Comment by Yourwon** [comment]
在prompt追加表示结束的标点符号，比如 ？。等，大概会改善这种情况。
