### ISSUE TITLE
 stream Responses print like this gif ？

### ISSUE THREAD

**Issue by 839781960** [TheoKanning/openai-java#121]
Stream Responses from OpenAI API with this project？ python use SSEclient ，could give some example 
like this   ![](https://miro.medium.com/v2/resize:fit:720/1*djLO6qi6_PCD0qmJtY5faw.gif)

**Comment by mrjiangyan** [comment]
I have resolved this issue, please see the pull request: https://github.com/TheoKanning/openai-java/pull/129

**Comment by TheoKanning** [comment]
This is fixed in 0.12.0
