### ISSUE TITLE
Software caused connection abort: recv failed

### ISSUE THREAD

**Issue by hengfeihu** [TheoKanning/openai-java#143]
![image](https://user-images.githubusercontent.com/14088102/222665952-b9d8ab56-0d38-4274-8d21-525d371ba53c.png)
为什么一直报这个错

**Comment by luoweiwei0908** [comment]
先告诉我，你是怎么设置代理的，为什么能访问，我要用http代理才行

**Comment by hengfeihu** [comment]
> 先告诉我，你是怎么设置代理的，为什么能访问，我要用http代理才行

代码第一行不就是，走系统代理
