### ISSUE TITLE
我在调用service.createChatCompletion的时候失败-

### ISSUE THREAD

**Issue by xiayana** [TheoKanning/openai-java#145]
![1677839847357](https://user-images.githubusercontent.com/40882709/222699277-0fbfdd45-c38b-4a84-b50f-c046b50eee8f.png)

是否有人和我遇到过同样的问题呢，请问是如何解决的？
Has anyone encountered the same problem as me, and how did you solve it?

**Comment by mzhu-ai** [comment]
No it works for me for this api, I am wondering if you have built your gradle project successfully.

**Comment by TheoKanning** [comment]
My only idea is gradle too. Did you double check your import statement?

**Comment by xiayana** [comment]
> 我唯一的想法也是gradle。您是否仔细检查了您的进口声明？

I found the problem, I made a stupid mistake myself
