### ISSUE TITLE
How to specify proxy

### ISSUE THREAD

**Issue by evin-zhang** [TheoKanning/openai-java#155]
When my request cannot directly reach the endpoint of openapi, I configured a proxy address. Normally, I can access the openapi endpoint with the proxy address, because I have no problem accessing the openapi endpoint with a browser.

`public OpenAiService(final String token, final String baseUrl, final Duration timeout) {
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        mapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
        OkHttpClient client = new OkHttpClient.Builder().proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 7890)))
                .addInterceptor(new AuthenticationInterceptor(token))
                .connectionPool(new ConnectionPool(5, 1, TimeUnit.SECONDS))
                .readTimeout(timeout.toMillis(), TimeUnit.MILLISECONDS)
                .addInterceptor(chain -> {
                    Request request = chain.request();
                    System.out.println("Request URL: " + request.url());
                    System.out.println("Request Method: " + request.method());
                    System.out.println("Request Headers: " + request.headers());
                    System.out.println("Request Body: " + request.body());
                    Response response = chain.proceed(request);
                    System.out.println("Response Code: " + response.code());
                    System.out.println("Response Headers: " + response.headers());
                    return response;
                })
                .build();

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(baseUrl)
                .client(client)
                .addConverterFactory(JacksonConverterFactory.create(mapper))
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .build();

        this.api = retrofit.create(OpenAiApi.class);
    }`

But my code throws exception like this :
`Exception in thread "main" java.lang.RuntimeException: java.net.SocketException: network unreachable
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:90)
        at io.reactivex.Single.blockingGet(Single.java:2002)
        at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:217)
        at com.theokanning.openai.service.OpenAiService.createCompletion(OpenAiService.java:88)
        at example.OpenAiApiExample.main(OpenAiApiExample.java:20)
Caused by: java.net.SocketException: network unreachable
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.theokanning.openai.service.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:26)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
        at io.reactivex.Observable.subscribe(Observable.java:10151)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:10151)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:2517)
        at io.reactivex.Single.blockingGet(Single.java:2001)`

**Comment by asleepyfish** [comment]
I extended the OpenAiService with subclasses and added proxies.
`public class OpenAiProxyService extends OpenAiService {
    private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(10L);

    public OpenAiProxyService(String token, String proxyHost, int proxyPort) {
        this(token, DEFAULT_TIMEOUT, proxyHost, proxyPort);
    }

    public OpenAiProxyService(String token, Duration timeout, String proxyHost, int proxyPort) {
        this(buildApi(token, timeout, proxyHost, proxyPort));
    }

    public OpenAiProxyService(OpenAiApi api) {
        super(api);
    }

    public static OpenAiApi buildApi(String token, Duration timeout, String proxyHost, int proxyPort) {
        ObjectMapper mapper = defaultObjectMapper();
        // Create proxy object
        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort));
        OkHttpClient client = defaultClient(token, timeout).newBuilder().proxy(proxy).build();
        Retrofit retrofit = defaultRetrofit(client, mapper);
        return retrofit.create(OpenAiApi.class);
    }
}`

**Comment by asleepyfish** [comment]
> When my request cannot directly reach the endpoint of openapi, I configured a proxy address. Normally, I can access the openapi endpoint with the proxy address, because I have no problem accessing the openapi endpoint with a browser.
> 
> `public OpenAiService(final String token, final String baseUrl, final Duration timeout) { ObjectMapper mapper = new ObjectMapper(); mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false); mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL); mapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE); OkHttpClient client = new OkHttpClient.Builder().proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 7890))) .addInterceptor(new AuthenticationInterceptor(token)) .connectionPool(new ConnectionPool(5, 1, TimeUnit.SECONDS)) .readTimeout(timeout.toMillis(), TimeUnit.MILLISECONDS) .addInterceptor(chain -> { Request request = chain.request(); System.out.println("Request URL: " + request.url()); System.out.println("Request Method: " + request.method()); System.out.println("Request Headers: " + request.headers()); System.out.println("Request Body: " + request.body()); Response response = chain.proceed(request); System.out.println("Response Code: " + response.code()); System.out.println("Response Headers: " + response.headers()); return response; }) .build();
> 
> ```
>     Retrofit retrofit = new Retrofit.Builder()
>             .baseUrl(baseUrl)
>             .client(client)
>             .addConverterFactory(JacksonConverterFactory.create(mapper))
>             .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
>             .build();
> 
>     this.api = retrofit.create(OpenAiApi.class);
> }`
> ```
> 
> But my code throws exception like this : `Exception in thread "main" java.lang.RuntimeException: java.net.SocketException: network unreachable at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45) at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:90) at io.reactivex.Single.blockingGet(Single.java:2002) at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:217) at com.theokanning.openai.service.OpenAiService.createCompletion(OpenAiService.java:88) at example.OpenAiApiExample.main(OpenAiApiExample.java:20) Caused by: java.net.SocketException: network unreachable at java.base/sun.nio.ch.Net.connect0(Native Method) at java.base/sun.nio.ch.Net.connect(Net.java:579) at java.base/sun.nio.ch.Net.connect(Net.java:568) at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) at java.base/java.net.Socket.connect(Socket.java:633) at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130) at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263) at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at com.theokanning.openai.service.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:26) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) at okhttp3.RealCall.execute(RealCall.java:81) at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46) at io.reactivex.Observable.subscribe(Observable.java:10151) at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) at io.reactivex.Observable.subscribe(Observable.java:10151) at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) at io.reactivex.Single.subscribe(Single.java:2517) at io.reactivex.Single.blockingGet(Single.java:2001)`

I extended the OpenAiService with subclasses and added proxies and it works well.
`public class OpenAiProxyService extends OpenAiService {
    private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(10L);

    public OpenAiProxyService(String token, String proxyHost, int proxyPort) {
        this(token, DEFAULT_TIMEOUT, proxyHost, proxyPort);
    }

    public OpenAiProxyService(String token, Duration timeout, String proxyHost, int proxyPort) {
        this(buildApi(token, timeout, proxyHost, proxyPort));
    }

    public OpenAiProxyService(OpenAiApi api) {
        super(api);
    }

    public static OpenAiApi buildApi(String token, Duration timeout, String proxyHost, int proxyPort) {
        ObjectMapper mapper = defaultObjectMapper();
        // Create proxy object
        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort));
        OkHttpClient client = defaultClient(token, timeout).newBuilder().proxy(proxy).build();
        Retrofit retrofit = defaultRetrofit(client, mapper);
        return retrofit.create(OpenAiApi.class);
    }
}`

**Comment by asleepyfish** [comment]
> When my request cannot directly reach the endpoint of openapi, I configured a proxy address. Normally, I can access the openapi endpoint with the proxy address, because I have no problem accessing the openapi endpoint with a browser.
> 
> `public OpenAiService(final String token, final String baseUrl, final Duration timeout) { ObjectMapper mapper = new ObjectMapper(); mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false); mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL); mapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE); OkHttpClient client = new OkHttpClient.Builder().proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 7890))) .addInterceptor(new AuthenticationInterceptor(token)) .connectionPool(new ConnectionPool(5, 1, TimeUnit.SECONDS)) .readTimeout(timeout.toMillis(), TimeUnit.MILLISECONDS) .addInterceptor(chain -> { Request request = chain.request(); System.out.println("Request URL: " + request.url()); System.out.println("Request Method: " + request.method()); System.out.println("Request Headers: " + request.headers()); System.out.println("Request Body: " + request.body()); Response response = chain.proceed(request); System.out.println("Response Code: " + response.code()); System.out.println("Response Headers: " + response.headers()); return response; }) .build();
> 
> ```
>     Retrofit retrofit = new Retrofit.Builder()
>             .baseUrl(baseUrl)
>             .client(client)
>             .addConverterFactory(JacksonConverterFactory.create(mapper))
>             .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
>             .build();
> 
>     this.api = retrofit.create(OpenAiApi.class);
> }`
> ```
> 
> But my code throws exception like this : `Exception in thread "main" java.lang.RuntimeException: java.net.SocketException: network unreachable at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45) at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:90) at io.reactivex.Single.blockingGet(Single.java:2002) at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:217) at com.theokanning.openai.service.OpenAiService.createCompletion(OpenAiService.java:88) at example.OpenAiApiExample.main(OpenAiApiExample.java:20) Caused by: java.net.SocketException: network unreachable at java.base/sun.nio.ch.Net.connect0(Native Method) at java.base/sun.nio.ch.Net.connect(Net.java:579) at java.base/sun.nio.ch.Net.connect(Net.java:568) at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) at java.base/java.net.Socket.connect(Socket.java:633) at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130) at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263) at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at com.theokanning.openai.service.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:26) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) at okhttp3.RealCall.execute(RealCall.java:81) at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46) at io.reactivex.Observable.subscribe(Observable.java:10151) at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) at io.reactivex.Observable.subscribe(Observable.java:10151) at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) at io.reactivex.Single.subscribe(Single.java:2517) at io.reactivex.Single.blockingGet(Single.java:2001)`

I extended the OpenAiService with subclasses and added proxies and it works well.
`
public class OpenAiProxyService extends OpenAiService {
    private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(10L);

    public OpenAiProxyService(String token, String proxyHost, int proxyPort) {
        this(token, DEFAULT_TIMEOUT, proxyHost, proxyPort);
    }

    public OpenAiProxyService(String token, Duration timeout, String proxyHost, int proxyPort) {
        this(buildApi(token, timeout, proxyHost, proxyPort));
    }

    public OpenAiProxyService(OpenAiApi api) {
        super(api);
    }

    public static OpenAiApi buildApi(String token, Duration timeout, String proxyHost, int proxyPort) {
        ObjectMapper mapper = defaultObjectMapper();
        // Create proxy object
        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort));
        OkHttpClient client = defaultClient(token, timeout).newBuilder().proxy(proxy).build();
        Retrofit retrofit = defaultRetrofit(client, mapper);
        return retrofit.create(OpenAiApi.class);
    }
}
`

**Comment by TheoKanning** [comment]
I added a section to the README on how to set up a proxy https://github.com/TheoKanning/openai-java#adding-a-proxy
