### ISSUE TITLE
gpt-3.5 model not supported

### ISSUE THREAD

**Issue by zhouxujing** [TheoKanning/openai-java#167]
This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

**Comment by marlonkerstens** [comment]
Need this also!

**Comment by TheoKanning** [comment]
The new `ChatCompletionRequest` object has what you're looking for :+1:

**Comment by LloydOllerhead-UnlikelyAI** [comment]
@TheoKanning I didn't think it was worth opening a new issue but just as a heads up:
using a non-chat model in a ChatCompletionRequest gives a pretty unhelpful error message (it just says `Invalid URL: /v1/chat/completions`), when all that is wrong is the model name. Might be a good candidate for review :)
