### ISSUE TITLE
Completion with gpt-3.5-turbo is currently not supported

### ISSUE THREAD

**Issue by kubecutle** [TheoKanning/openai-java#187]
I get the following error when trying to use gpt-3.5-turbo model. Is there a plan to support this model?

``
com.theokanning.openai.OpenAiHttpException: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?
	at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:220)

``

**Comment by HendSame** [comment]
You should use ```createChatCompletion()```.

**Comment by ahmedaa6122** [comment]
> You should use `createChatCompletion()`.

Can send me example please

**Comment by ahmedaa6122** [comment]
@HendSame can send me example please

**Comment by kubecutle** [comment]
It looks like this has not been pushed to maven repo yet.

**Comment by kubecutle** [comment]
Maven repo is still at 0.11.0 while github is at 0.19.0 already. It would be very much appreciated if the latest could be published to maven central.

**Comment by HendSame** [comment]
> @HendSame can send me example please

Refer to the API documentation: https://platform.openai.com/docs/api-reference/chat/create

Code example:
```
        String token = System.getenv("OPENAI_TOKEN");
        OpenAiService service = new OpenAiService(token);

        List<ChatMessage> chatMessageList = new ArrayList<>();
        ChatMessage chatMessage = new ChatMessage();
        chatMessage.setContent("Hello!");
        chatMessage.setRole("user");
        chatMessageList.add(chatMessage);

        ChatCompletionRequest chatCompletionRequest = ChatCompletionRequest.builder()
                                                                           .model("gpt-3.5-turbo")
                                                                           .messages(chatMessageList).build();
       service.createChatCompletion(chatCompletionRequest);
```

**Comment by HendSame** [comment]
> It looks like this has not been pushed to maven repo yet.

Yes, current version（0.19.0） is required. You can compile it by yourself.

**Comment by TheoKanning** [comment]
`createChatCompletion` should be supported in 0.11.0

I have a few changes going out in 0.11.1 but they're all minor

**Comment by kubecutle** [comment]
Thanks. I did compile and it works great. I would be thrilled to see an example that uses streaming. Or some explanation of how to get the incremental content from openai server.
