### ISSUE TITLE
Add user id parameter to CompletionRequest

### ISSUE THREAD

**Issue by aleclarin** [TheoKanning/openai-java#19]
First off, thanks for putting this library together, it's super helpful!

[OpenAI's App Review/Usage Guidelines](https://beta.openai.com/docs/usage-guidelines/what-is-required-for-my-application-to-be-approved) require requests to include the end-user ID:

> All applications are required to receive approval through an [App Review](https://beta.openai.com/docs/usage-guidelines/app-review) and to [send end-user IDs](https://beta.openai.com/docs/usage-guidelines/4-know-your-customers) with each request

Currently there's no [user ID parameter](https://beta.openai.com/docs/api-reference/completions/create#completions/create-user) in CompletionRequest.

**Comment by gbolcer** [comment]
Okay, read through the documentation.  It should be easy to add .user("userwhatever") to the constructor.  Let me see if I can do it myself and submit it.  

'''
response = openai.Completion.create(
  model="text-davinci-002",
  prompt="This is a test",
  max_tokens=5,
  user="user123456"
)
'''

**Comment by TheoKanning** [comment]
Thanks for telling me about this!
