### ISSUE TITLE
best candidate for streaming support ?

### ISSUE THREAD

**Issue by jiangying000** [TheoKanning/openai-java#201]
There are some PR awaiting review, which one is to be chosen ?

they are (order by time):
 
https://github.com/TheoKanning/openai-java/pull/129
https://github.com/TheoKanning/openai-java/pull/183
https://github.com/TheoKanning/openai-java/pull/186
https://github.com/TheoKanning/openai-java/pull/195

**Comment by TheoKanning** [comment]
I'm looking through them and I hope to include streaming in the next update 👍

**Comment by 1760643468** [comment]
Support 195
