### ISSUE TITLE
Can you please develop a stream client using Reactor Java? Because Reactor is very fast and easy to use.

### ISSUE THREAD

**Issue by MrWangGang** [TheoKanning/openai-java#217]
Can you please develop a stream client using Reactor Java? Because Reactor is very fast and easy to use.

**Comment by MrWangGang** [comment]
thanks, this is important to my current job

**Comment by reactiveclown** [comment]
@MrWangGang Kindly see the https://github.com/reactiveclown/openai-webflux-java
The work for SSE implementation is currenlty ongoing and will be implemented in the nearest future.

**Comment by MrWangGang** [comment]
thanks
