### ISSUE TITLE
I want to build gradle project,but ran into some problems

### ISSUE THREAD

**Issue by stoneHah** [TheoKanning/openai-java#220]
I know how to build a maven project, execute **mvn clean install** on the console, and then the jar package information can be entered into the local maven warehouse.
Since I don't know much about gradle, I also tried to search on Google, and found that I didn't find a suitable command similar to mvn clean package. Who can help me?
I just want to package the latest code into the maven repository, and then other projects can add this dependency

**Comment by stoneHah** [comment]
I tried to use vscode to open the project, and then executed the publishToMavenLocal task. It seems that the literal meaning is what I want, but I am not sure if it is. ended up running into this problem:
`> Task :client:signMavenPublication FAILED
<=========----> 69% EXECUTING [1s]
> IDLE
> IDLE
> :api:simpleJavadocJar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':client:signMavenPublication'.
> Cannot perform signing task ':client:signMavenPublication' because it has no configured signatory

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
20 actionable tasks: 8 executed, 12 up-to-date
Could not execute build using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.0.2-bin.zip'.`

**Comment by yiboji** [comment]
run into the same problem. I guess this requires digital signature, tho I'm not familiar with it.
