### ISSUE TITLE
Can I get usage of tokens while using streamChatCompletion method? 

### ISSUE THREAD

**Issue by SparrowBo** [TheoKanning/openai-java#223]
ChatCompletionChunk object do not have field which save usage of token, and it's not easy for java to count tokens

**Comment by n3bul4** [comment]
@SparrowBo 
Sadly, OpenAI API doesn't support tokens on completion or chatcompletion chunks. 

You can read about the downsides of using streaming here:
[https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb)

> Downsides
Another small drawback of streaming responses is that the response **no longer includes the usage field to tell you how many tokens were consumed.** After receiving and combining all of the responses, you can calculate this yourself using [tiktoken](https://github.com/openai/openai-cookbook/blob/1f6c2304b401e931928e74e978d9a0b8a40d1cf7/examples/How_to_count_tokens_with_tiktoken.ipynb).

**Comment by SparrowBo** [comment]
it's helpful, thanks
