### ISSUE TITLE
请问支持代理地址吗？

### ISSUE THREAD

**Issue by wangpre** [TheoKanning/openai-java#234]
就是自己搭建反向代理服务，用我的域名替换 api.openai.com

**Comment by oursy** [comment]
`new OpenAiService(final OpenAiApi api, final ExecutorService executorService)` use this constructor

**Comment by wangpre** [comment]
> https://github.com/TheoKanning/openai-java#adding-a-proxy

不是用proxy，是使用第三方的代理接口地址直接代替官方的接口地址，比如 https://api.openai-proxy.com

**Comment by SparrowBo** [comment]
/**
     * Creates a new OpenAiService that wraps OpenAiApi.
     * The ExecutorService must be the one you get from the client you created the api with
     * otherwise shutdownExecutor() won't work.
     * <p>
     * Use this if you need more customization.
     *
     * @param api             OpenAiApi instance to use for all methods
     * @param executorService the ExecutorService from client.dispatcher().executorService()
     */
    public OpenAiService(final OpenAiApi api, final ExecutorService executorService) {
        this.api = api;
        this.executorService = executorService;
    }

源码中提供了这种构造方式，你通过这种构造方式创建的 OpenAiService 可以是自己的域名，而不是用默认的域名

**Comment by xhxgit** [comment]
> `new OpenAiService(final OpenAiApi api, final ExecutorService executorService)` use this constructor

If you are not sure how to use it, you can refer to this constructor — `public OpenAiService(final String token, final Duration timeout)` or the example below.

```
ObjectMapper mapper = OpenAiService.defaultObjectMapper();
OkHttpClient client = OpenAiService.defaultClient("sr-xxxx", Duration.ofSeconds(10));
Retrofit retrofit = new Retrofit.Builder()
        .baseUrl("https://api.notopenai.com/")
        .client(client)
        .addConverterFactory(JacksonConverterFactory.create(mapper))
        .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
        .build();
OpenAiService service = new OpenAiService(retrofit.create(OpenAiApi.class), client.dispatcher().executorService());
```
