### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by ASinby** [TheoKanning/openai-java#239]
使用的是2020.1 IDEA，代码如下：
```java
ChatCompletionRequest chatCompletionRequest = ChatCompletionRequest.builder()
                .model(chatgptConfig.getModel())
                .messages(chatList)
                .n(3)
                .maxTokens(50)
                .build();

OpenAiService service = new OpenAiService(chatgptConfig.getApiKey());
// 👇👇为哈在这儿一直超时呢，本地梯子已搭
ChatCompletionResult result = service.createChatCompletion(chatCompletionRequest);
// 👆👆
Map<String, String> r = new HashMap<>();
String content = result.getChoices().get(0).getMessage().getContent();
r.put("回答", content);
````

**Comment by MuDeng0** [comment]
开全局，在代码中加上proxy

**Comment by MuDeng0** [comment]
> 使用的是2020.1 IDEA，代码如下：
> 
> ```java
> ChatCompletionRequest chatCompletionRequest = ChatCompletionRequest.builder()
>                 .model(chatgptConfig.getModel())
>                 .messages(chatList)
>                 .n(3)
>                 .maxTokens(50)
>                 .build();
> 
> OpenAiService service = new OpenAiService(chatgptConfig.getApiKey());
> // 👇👇为哈在这儿一直超时呢，本地梯子已搭
> ChatCompletionResult result = service.createChatCompletion(chatCompletionRequest);
> // 👆👆
> Map<String, String> r = new HashMap<>();
> String content = result.getChoices().get(0).getMessage().getContent();
> r.put("回答", content);
> ```
开全局，在代码中加上proxy

**Comment by FlyingBird-DGU** [comment]
加个proxy，指向你梯子的端口
`        var url = new URL(httpsProxy);

        var objectMapper = defaultObjectMapper();
        var proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(url.getHost(), url.getPort()));//这里
        var client = defaultClient(openaiApiKey, Duration.ofSeconds(10))
                .newBuilder()
                .proxy(proxy)//这里
                .build();
        var retrofit = defaultRetrofit(client, objectMapper);
        var api = retrofit.create(OpenAiApi.class);
        var service = new OpenAiService(api);

        var chatCompletionRequest = ChatCompletionRequest.builder()
                .messages(List.of(new ChatMessage(SYSTEM.value(), requestProps.getSystemMessage()), new ChatMessage(USER.value(), requestProps.getPrompt())))
                .model("gpt-3.5-turbo")
                .maxTokens(1000)
                .stream(true)
                .temperature(0.8)
                .topP(1d)
                .presencePenalty(1d)
                .build();

        service.streamChatCompletion(chatCompletionRequest).forEach(System.out::println);
`

**Comment by ASinby** [comment]
> > 使用的是2020.1 IDEA，代码如下：
> > ```java
> > ChatCompletionRequest chatCompletionRequest = ChatCompletionRequest.builder()
> >                 .model(chatgptConfig.getModel())
> >                 .messages(chatList)
> >                 .n(3)
> >                 .maxTokens(50)
> >                 .build();
> > 
> > OpenAiService service = new OpenAiService(chatgptConfig.getApiKey());
> > // 👇👇为哈在这儿一直超时呢，本地梯子已搭
> > ChatCompletionResult result = service.createChatCompletion(chatCompletionRequest);
> > // 👆👆
> > Map<String, String> r = new HashMap<>();
> > String content = result.getChoices().get(0).getMessage().getContent();
> > r.put("回答", content);
> > ```
> 
> 开全局，在代码中加上proxy

3Q，解决啦

**Comment by ASinby** [comment]
> 加个proxy，指向你梯子的端口 ` var url = new URL(httpsProxy);
> 
> ```
>     var objectMapper = defaultObjectMapper();
>     var proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(url.getHost(), url.getPort()));//这里
>     var client = defaultClient(openaiApiKey, Duration.ofSeconds(10))
>             .newBuilder()
>             .proxy(proxy)//这里
>             .build();
>     var retrofit = defaultRetrofit(client, objectMapper);
>     var api = retrofit.create(OpenAiApi.class);
>     var service = new OpenAiService(api);
> 
>     var chatCompletionRequest = ChatCompletionRequest.builder()
>             .messages(List.of(new ChatMessage(SYSTEM.value(), requestProps.getSystemMessage()), new ChatMessage(USER.value(), requestProps.getPrompt())))
>             .model("gpt-3.5-turbo")
>             .maxTokens(1000)
>             .stream(true)
>             .temperature(0.8)
>             .topP(1d)
>             .presencePenalty(1d)
>             .build();
> 
>     service.streamChatCompletion(chatCompletionRequest).forEach(System.out::println);
> ```
> 
> `

谢谢

**Comment by shenbaoNew** [comment]
请问 chatgptConfig.getProxyIp() 这里的ip地址具体是哪里的
