### ISSUE TITLE
关于停止聊天流的问题

### ISSUE THREAD

**Issue by HOPPINZQ** [TheoKanning/openai-java#248]
![image](https://user-images.githubusercontent.com/58420107/230784491-ef3a5230-640e-4a73-996e-47978d343eb9.png)
如图，我想要在对话流输出的时候及时停止输出，我该如何做呢？
类似下面这个功能。
![image](https://user-images.githubusercontent.com/58420107/230784672-6fdb517b-789f-41fc-9e53-95ccf6b0295c.png)

**Comment by FlyingBird-DGU** [comment]
调用io.reactivex.subscribers.DisposableSubscriber#cancel或者io.reactivex.subscribers.DisposableSubscriber#dispose，不知道你是不是这个意思

**Comment by ASSDOMINATE** [comment]
前端执行SSE的close ，后端监听SSE的close，OpenAiService是流模式的话执行shutdownExecutor就行了

**Comment by HOPPINZQ** [comment]
> 前端执行SSE的close ，后端监听SSE的close，OpenAiService是流模式的话执行shutdownExecutor就行了

懂了
