### ISSUE TITLE
How to separate the message results from the streaming?  Such as sending the stream result to websocket

### ISSUE THREAD

**Issue by cooltheo** [TheoKanning/openai-java#256]
**I now need to stream the results back through a websocket, but I can only do this within blockingForEach. What are the other ways?**
**Environment**
Java info

`Java 11`

Maven info

```xml
<properties>
        <openai-gpt3-java-service.version>0.12.0</openai-gpt3-java-service.version>
        <openai-gpt3-java-api.version>0.12.0</openai-gpt3-java-api.version>
        <openai-gpt3-java-client.version>0.12.0</openai-gpt3-java-client.version>
    </properties>
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>com.theokanning.openai-gpt3-java</groupId>
            <artifactId>service</artifactId>
            <version>${openai-gpt3-java-service.version}</version>
        </dependency>
        <dependency>
            <groupId>com.theokanning.openai-gpt3-java</groupId>
            <artifactId>api</artifactId>
            <version>${openai-gpt3-java-api.version}</version>
        </dependency>
        <dependency>
            <groupId>com.theokanning.openai-gpt3-java</groupId>
            <artifactId>client</artifactId>
            <version>${openai-gpt3-java-client.version}</version>
        </dependency>
    </dependencies>
```

**Code**
**I want to separate sending messages from streaming results.** 
In this way i just can send message in the blockingForEach, so this would result in unnecessary crossover. 

```java
// Open ai response by stream
        this.openAiService.streamChatCompletion(chatCompletionRequest)
                .doOnError(e -> {
                    log.error("OPEN_AI_CHAT_STREAM_ERROR", e);
                })
                .delay(1, TimeUnit.SECONDS, false)
                .blockingForEach(nextData -> {
                    String nextDataContent = nextData.getChoices().get(0).getMessage().getContent();
                    log.debug("OPEN_AI_STREAM_NEXT_DATA|{}", nextData);
                    MessageQO messageQo = new MessageQO();
                    messageQo.setFrom("test");
                    messageQo.setTo("test");
                    messageQo.setContent(nextDataContent);
                    this.sendWsMessage(messageQo);
                });
```

I tried this way but failed

```java
Iterable <ChatCompletionChunk> chunkResult = this.openAiService.streamChatCompletion(chatCompletionRequest)
                .doOnError(e -> {
                    log.error("OPEN_AI_CHAT_STREAM_ERROR", e);
                })
                .delay(1, TimeUnit.SECONDS, false)
                .blockingIterable();

        log.debug("OPEN_AI_STREAM_CHUNK|{}", chunkResult);
        this.openAiService.shutdownExecutor();


// Get the chunk response
StringBuilder sb = new StringBuilder();
Iterable<ChatCompletionChunk> chunkResult = chatGpt.stream(qo);
        Iterator<ChatCompletionChunk> aiIt = chunkResult.iterator();
        while (aiIt.hasNext()) {
            sb.append(aiIt.next().toString());
        }
        return sb.toString();
```

Error info

```java
java.lang.RuntimeException: java.io.InterruptedIOException: executor rejected
```

What should i do? Or other implement way? Thank you very much!

**Comment by cooltheo** [comment]
Who can show the example?

**Comment by cooltheo** [comment]
Who can show the example?

**Comment by greek-zzf** [comment]
like this，you can handle elements in `convertAndsendResponse` method 
```java 
Disposable subscribe = openAiService.streamChatCompletion(chatCompletionRequest)
                .doOnSubscribe(e -> startHandle(userIdentity))
                .subscribe(chat -> convertAndSendResponse(chat),
                        throwable -> errorHandle(throwable),
                        () -> completeHandle());

**Comment by cooltheo** [comment]
> like this，you can handle elements in `convertAndsendResponse` method
> 
> ```java
> Disposable subscribe = openAiService.streamChatCompletion(chatCompletionRequest)
>                 .doOnSubscribe(e -> startHandle(userIdentity))
>                 .subscribe(chat -> convertAndSendResponse(chat),
>                         throwable -> errorHandle(throwable),
>                         () -> completeHandle());
> ```

Thank you for answering.
Well could you please show me, how to consume the disposable item?

**Comment by RicardoMiki** [comment]
I have encountered the same problem, is there a good solution now?@cooltheo

**Comment by cooltheo** [comment]
Here is my solution, and the pseudo-code. You can process the chunk message by using doProcessStreamMessage or using the callback function. @wanghaowei0107 

`
public LLMChatGptVo streamChat(final LLMChatGptQo qo, LLMCallbackService callback) {
        // Params check
        this.checkChat(qo);

        // Build chat messages
        ArrayList<ChatMessage> chatMessageList = this.buildChatMessages(qo);
        
        // Build open ai request params
        ChatCompletionRequest chatCompletionRequest = this.buildChatCompletionRequest(qo, chatMessageList);

        LLMChatGptVo LLMChatGptVo = new LLMChatGptVo();

        // Set custom thread poll
        Scheduler customScheduler = Schedulers.from(executor);
        try {
            this.openAiService.streamChatCompletion(chatCompletionRequest)
                    .observeOn(customScheduler)
                    .doOnSubscribe(e -> {
                        this.beforeProcessStreamMessage();
                        log.info("STREAM_CHAT_SUBSCRIBE|{}", e);
                    })
                    .subscribe(
                            chunkResponse -> {
                                if (this.checkAiGc(chunkResponse)) {
                                    String chunkResponseContent = chunkResponse.getChoices().get(0).getMessage().getContent();
                                    // Build chunk dto
                                    StreamChatDto streamChatDto = StreamChatDto.builder()
                                            .id(chunkResponse.getId())
                                            .currentContent(chunkResponseContent)
                                            .supplementContent(aiGcResult.toString())
                                            .createdAt(chunkResponse.getCreated())
                                            .build();
                                    callback.onHandle(streamChatDto);
                                }
                                log.debug("STREAM_CHAT_RESPONSE_CHUNK|{}", chunkResponse);
                                this.doProcessStreamMessage(chunkResponse, qo);
                            },
                            error -> {
                                log.error("STREAM_CHAT_ERROR", error);
                                callback.onError(error);
                            },
                            () -> {
                            log.info("STREAM_CHAT_FINISHED|{}", DateUtil.now());
                                callback.onSuccess(streamChatDto);
                            }
                    );
        } catch (Exception e) {
            throw new BizException(ErrorCodeEnum.BIZ_ENGINE_OPEN_AI_CALL_FAILED.getCode());
        }

}
`

**Comment by cooltheo** [comment]
Here is my solution, and the pseudo-code. You can process the chunk message by using doProcessStreamMessage or using the callback function. @wanghaowei0107

`public LLMChatGptVo streamChat(final LLMChatGptQo qo, LLMCallbackService callback) {
        // Params check
        this.checkChat(qo);

        // Build chat messages
        ArrayList<ChatMessage> chatMessageList = this.buildChatMessages(qo);
        
        // Build open ai request params
        ChatCompletionRequest chatCompletionRequest = this.buildChatCompletionRequest(qo, chatMessageList);

        LLMChatGptVo LLMChatGptVo = new LLMChatGptVo();

        // Set custom thread poll
        Scheduler customScheduler = Schedulers.from(executor);
        try {
            this.openAiService.streamChatCompletion(chatCompletionRequest)
                    .observeOn(customScheduler)
                    .doOnSubscribe(e -> {
                        this.beforeProcessStreamMessage();
                        log.info("STREAM_CHAT_SUBSCRIBE|{}", e);
                    })
                    .subscribe(
                            chunkResponse -> {
                                if (this.checkAiGc(chunkResponse)) {
                                    String chunkResponseContent = chunkResponse.getChoices().get(0).getMessage().getContent();
                                    // Build chunk dto
                                    StreamChatDto streamChatDto = StreamChatDto.builder()
                                            .id(chunkResponse.getId())
                                            .currentContent(chunkResponseContent)
                                            .supplementContent(aiGcResult.toString())
                                            .createdAt(chunkResponse.getCreated())
                                            .build();
                                    callback.onHandle(streamChatDto);
                                }
                                log.debug("STREAM_CHAT_RESPONSE_CHUNK|{}", chunkResponse);
                                this.doProcessStreamMessage(chunkResponse, qo);
                            },
                            error -> {
                                log.error("STREAM_CHAT_ERROR", error);
                                callback.onError(error);
                            },
                            () -> {
                            log.info("STREAM_CHAT_FINISHED|{}", DateUtil.now());
                                callback.onSuccess(streamChatDto);
                            }
                    );
        } catch (Exception e) {
            throw new BizException(ErrorCodeEnum.BIZ_ENGINE_OPEN_AI_CALL_FAILED.getCode());
        }

}`

**Comment by cooltheo** [comment]
Here is my solution, and the pseudo-code. You can process the chunk message by using doProcessStreamMessage or using the callback function. @wanghaowei0107

```
public LLMChatGptVo streamChat(final LLMChatGptQo qo, LLMCallbackService callback) {
        // Params check
        this.checkChat(qo);

        // Build chat messages
        ArrayList<ChatMessage> chatMessageList = this.buildChatMessages(qo);
        
        // Build open ai request params
        ChatCompletionRequest chatCompletionRequest = this.buildChatCompletionRequest(qo, chatMessageList);

        LLMChatGptVo LLMChatGptVo = new LLMChatGptVo();

        // Set custom thread poll
        Scheduler customScheduler = Schedulers.from(executor);
        try {
            this.openAiService.streamChatCompletion(chatCompletionRequest)
                    .observeOn(customScheduler)
                    .doOnSubscribe(e -> {
                        this.beforeProcessStreamMessage();
                        log.info("STREAM_CHAT_SUBSCRIBE|{}", e);
                    })
                    .subscribe(
                            chunkResponse -> {
                                if (this.checkAiGc(chunkResponse)) {
                                    String chunkResponseContent = chunkResponse.getChoices().get(0).getMessage().getContent();
                                    // Build chunk dto
                                    StreamChatDto streamChatDto = StreamChatDto.builder()
                                            .id(chunkResponse.getId())
                                            .currentContent(chunkResponseContent)
                                            .supplementContent(aiGcResult.toString())
                                            .createdAt(chunkResponse.getCreated())
                                            .build();
                                    callback.onHandle(streamChatDto);
                                }
                                log.debug("STREAM_CHAT_RESPONSE_CHUNK|{}", chunkResponse);
                                this.doProcessStreamMessage(chunkResponse, qo);
                            },
                            error -> {
                                log.error("STREAM_CHAT_ERROR", error);
                                callback.onError(error);
                            },
                            () -> {
                            log.info("STREAM_CHAT_FINISHED|{}", DateUtil.now());
                                callback.onSuccess(streamChatDto);
                            }
                    );
        } catch (Exception e) {
            throw new BizException(ErrorCodeEnum.BIZ_ENGINE_OPEN_AI_CALL_FAILED.getCode());
        }

}
```
