### ISSUE TITLE
Whether to query the token balance（是否支持查询token余额）

### ISSUE THREAD

**Issue by PanXJin** [TheoKanning/openai-java#267]
我发现项目中似乎没有查看当前token余额的一个方式

**Comment by BuGeChenkehao** [comment]
都一个月了，还没更细，有没有老哥写一个啊

**Comment by louisice** [comment]
官方接口废弃了，所以相关的功能都没了。要么就自己实现一个计算token的逻辑，但也不能确保跟官方统计是完全一致的，尤其是一个key多个地方用的情况
