### ISSUE TITLE
如何创建连续对话

### ISSUE THREAD

**Issue by 1351383118** [TheoKanning/openai-java#268]
构造ChatCompletionRequest对象，里面没有可以set会话id的选项，创建ChatCompletionResult对象之后有一个会话id，这个id在哪里可以使用呢？我的理解是，有了这个id，是不是可以在下次构建聊天ChatCompletionRequest对象的时候附带过去，但是我没有找到在哪里可以使用。

**Comment by Tomotopieces** [comment]
那个id就是个摆设···，每次都需要将完整对话上下文发送给gpt。就算是[Auto-GPT](https://github.com/Significant-Gravitas/Auto-GPT)也都是这么做的

看[example](https://github.com/TheoKanning/openai-java/blob/main/example/src/main/java/example/OpenAiApiExample.java)的 38 ~ 40 行

记得把issue close掉

---

That ID is just for show… every time, the complete conversation context needs to be sent to GPT. Even [Auto-GPT](https://github.com/Significant-Gravitas/Auto-GPT) works this way.

Refer to lines 38 to 40 of the [example](https://github.com/TheoKanning/openai-java/blob/main/example/src/main/java/example/OpenAiApiExample.java).

remember to close the issue

**Comment by 1351383118** [comment]
> 那个id就是个摆设···，每次都需要将完整对话上下文发送给gpt。就算是[Auto-GPT](https://github.com/Significant-Gravitas/Auto-GPT)也都是这么做的
> 
> 看[example](https://github.com/TheoKanning/openai-java/blob/main/example/src/main/java/example/OpenAiApiExample.java)的 38 ~ 40 行
> 
> 记得把issue close掉
> 
> That ID is just for show… every time, the complete conversation context needs to be sent to GPT. Even [Auto-GPT](https://github.com/Significant-Gravitas/Auto-GPT) works this way.
> 
> Refer to lines 38 to 40 of the [example](https://github.com/TheoKanning/openai-java/blob/main/example/src/main/java/example/OpenAiApiExample.java).
> 
> remember to close the issue

好吧，我找了好久，确实没发现哪里可以使用。我一度以为自己漏掉了什么东西。
