### ISSUE TITLE
ChatCompletionRequest gpt-3.5-turbo message null

### ISSUE THREAD

**Issue by maxiplay** [TheoKanning/openai-java#271]
I am trying to use the streaming call API to gpt-3.5-turbo but the chunks (ChatCompletionChunk) have null message during streaming.

Here my code:
`@Test
    public void testOpenAI() throws InterruptedException {

        OpenAiService service = new OpenAiService("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", Duration.ofSeconds(60));

        List<ChatMessage> chatMessageList = new ArrayList<>();
        ChatMessage chatMessage = new ChatMessage();
        chatMessage.setContent("Give me a novel idea");
        chatMessage.setRole("user");
        chatMessageList.add(chatMessage);

        ChatCompletionRequest chatCompletionRequest = ChatCompletionRequest.builder()
                .model("gpt-3.5-turbo")
                .stream(true)
                .messages(chatMessageList).build();

        service.streamChatCompletion(chatCompletionRequest).subscribe(chatCompletionChunk -> System.out.println(chatCompletionChunk));

        while (true) {
            //do something
            Thread.sleep(1000);
        }

    }`

And streamed results

ChatCompletionChunk(id=chatcmpl-7ADamstt0oGx75yykWVGgqpi17twD, object=chat.completion.chunk, created=1682669884, model=gpt-3.5-turbo-0301, choices=[ChatCompletionChoice(index=0, message=null, finishReason=null)])
ChatCompletionChunk(id=chatcmpl-7ADamstt0oGx75yykWVGgqpi17twD, object=chat.completion.chunk, created=1682669884, model=gpt-3.5-turbo-0301, choices=[ChatCompletionChoice(index=0, message=null, finishReason=null)])
ChatCompletionChunk(id=chatcmpl-7ADamstt0oGx75yykWVGgqpi17twD, object=chat.completion.chunk, created=1682669884, model=gpt-3.5-turbo-0301, choices=[ChatCompletionChoice(index=0, message=null, finishReason=null)])
ChatCompletionChunk(id=chatcmpl-7ADamstt0oGx75yykWVGgqpi17twD, object=chat.completion.chunk, created=1682669884, model=gpt-3.5-turbo-0301, choices=[ChatCompletionChoice(index=0, message=null, finishReason=null)])

Somebody here has different results ?

**Comment by oferavnery** [comment]
Same issue for me for streamed results

**Comment by simatuzheng** [comment]
这个问题解决了吗，sir

**Comment by rogertad** [comment]
same over here
