### ISSUE TITLE
[50$ bounty] need help to update the UI during the incoming stream

### ISSUE THREAD

**Issue by jasperbeckers** [TheoKanning/openai-java#281]
I'm having major trouble updating a text field with each incoming token of the stream. I have tried multiple approaches none of which work. Note I'm developing a keyboard so I cannot call runOnUiThread (there is no base activity).

**A)**
`service.streamChatCompletion(chatCompletionRequest).blockingIterable()`
This seems to return the iterable only when it has received the full stream, so I cannot update on each token.

**B)**
`service.streamChatCompletion(chatCompletionRequest).elementAt()`
The idea is to call one by one and update the UI in between, However, the second time I get `IllegalStateException: Already executed.`.

**C)**
`service.streamChatCompletion(chatCompletionRequest).subscribe(new Consumer<ChatCompletionChunk>() {
@Override
public void accept(ChatCompletionChunk chatCompletionChunk) throws Exception {update view}})`
This calls the view updates upon each incoming token but it does not draw the updated view until the stream is finished. This happens also with blockingForEach and forEach.

The person that helps me solve this issue I will send 50$ via PayPal.

**Comment by drakeet** [comment]
Try set `callbackExecutor(RxSchedulerToExecutor(Schedulers.io()))` on Retrofit
![image](https://github.com/TheoKanning/openai-java/assets/5214214/084bb369-62d7-4c5c-9bef-2f5df1073825)

**Comment by jasperbeckers** [comment]
Thanks drakeet, to make this change do I need to fork the project and then import module in Android Studio? Do I need to build service, api and client in any particular order? I get `Plugin with id 'com.vanniktech.maven.publish' not found.` when building api.

> Try set `callbackExecutor(RxSchedulerToExecutor(Schedulers.io()))` on Retrofit
> 
> // The Chinese comment is saying: Otherwise it will block the main thread.
> 
> ![image](https://user-images.githubusercontent.com/5214214/238348888-084bb369-62d7-4c5c-9bef-2f5df1073825.png)

**Comment by drakeet** [comment]
> Thanks @drakeet , to make this change do I have to rebuild OpenAiService or is there an easier way?

You can make a quick try: copy the source code of OpenAiService.java, then modify it and use it.

**Comment by jasperbeckers** [comment]
I got it to work, thanks a lot! I ended up using `.callBackExecutor(scheduler)` which I defined on the main thread. Want to claim the bounty? Let me know your paypal mail.
