### ISSUE TITLE
Here is a response with markdown using  com.theokanning.openai.service.OpenAiService#streamChatCompletion  , it seems "\n" is missing?

### ISSUE THREAD

**Issue by yqxu** [TheoKanning/openai-java#282]
Response as bellow:

Hello! It seems that you would like a long markdown-formatted text. Let me provide an example for you: ``` # AIgure: AI Character Generators AIgure is an innovative AI-driven digital companion software that combines the power of blockchain and artificial intelligence. ## Key Features - **Highly Personalized**: AIgure provides creators with unique and customizable digital companions. - **Easily Customizable**: Simple and user-friendly tools make customization a breeze. - **Emotionally Intelligent**: AIgure characters have a deep understanding of human emotions with the help of advanced NLP techniques, providing more empathetic interactions with users. ## Applications 1. **Game Development**: AIgure's digital companions can enhance player engagement and experience. 2. **Marketing**: AIgure can help brands build better personal relationships with their customers. 3. **Therapeutic Communication**: AIgure can provide assistance for mental health support or personal growth. 4. **Education**: AIgure characters can facilitate interactive learning and generate intelligent tutoring solutions. ## Core Technologies ### Blockchain - AIgure's blockchain integration ensures the security and authenticity of the digital characters. - Smart contracts handle character personalization and rights management. ### Artificial Intelligence - Advanced AI technology empowers AIgure's digital characters with intelligence and emotional understanding. - The combination of NLP and large language models provides rich interactive experiences. ## Summary AIgure is a groundbreaking digital companion software designed to deliver unparalleled personalized experiences, powered by blockchain and artificial intelligence technologies. ``` Select one of the following questions to continue our discussion: 1. How does AIgure's integration with blockchain technology ensure security? 2. What are the benefits of using AIgure in game development? 3. How can AIgure be used in marketing campaigns to build better personal relationships?

 It seems "\n" is missing?

**Comment by yqxu** [comment]
Can ObjectMapper add logic to escape line breaks \n to \\n ?

**Comment by qclucky7** [comment]
ObjectMapper jsonMapper = new ObjectMapper() .enable(SerializationFeature.INDENT_OUTPUT)
