### ISSUE TITLE
Chat-completion function-call

### ISSUE THREAD

**Issue by lumiseven** [TheoKanning/openai-java#295]
[feature]
2023-06-13, OpenAI release new model(gpt-3.5-turbo-0613) which support new param 'functions' and 'function-call' [function-call](https://platform.openai.com/docs/api-reference/chat/create#chat/create-functions)

functions: A list of functions the model may generate JSON inputs for.

function_call: Controls how the model responds to function calls. "none" means the model does not call a function, and responds to the end-user. "auto" means the model can pick between an end-user or calling a function. Specifying a particular function via {"name":\ "my_function"} forces the model to call that function. "none" is the default when no functions are present. "auto" is the default if functions are present.

**Comment by Eduardo-T** [comment]
I created a fork adding the new capabilities @lumiseven , check it out: https://github.com/Eduardo-T/openai-java-20240614
