### ISSUE TITLE
When to support the GPT's new update (20240614 function call)?

### ISSUE THREAD

**Issue by cooltheo** [TheoKanning/openai-java#296]
Hi there, here we want to use the new feature: function call by java sdk, and when can we support it?

Functions is an optional parameter in the ChatCompletion API which can be used to provide function specifications. The purpose of this is to enable models to generate outputs which adhere to function input schemas. Note that the API will not actually execute any function calls. It is up to developers to execute function calls using model outputs.

If the functions parameter is provided then by default the model will decide when it is appropriate to use one of the functions. The API can also be forced to use a specific function by setting the function_call parameter to {"name": "<insert-function-name>"}. If a function is used, the output will contain "finish_reason": "function_call" in the response, as well as a function_call object that has the name of the function and the generated function arguments.

Functions are specified with the following fields:

Name: The name of the function.
Description: A description of what the function does. The model will use this to decide when to call the function.
Parameters: The parameters object contains all of the input fields the function requires. These inputs can be of the following types: String, Number, Boolean, Object, Null, AnyOf. Refer to the [API reference docs](https://platform.openai.com/docs/api-reference/chat) for details.
Required: Which of the parameters are required to make a query. The rest will be treated as optional.

**Comment by Eduardo-T** [comment]
I created a fork adding the new capabilities @AlfySoftware @cooltheo , check it out: https://github.com/Eduardo-T/openai-java-20240614

**Comment by davidb-e4s** [comment]
@Eduardo-T great work...sorry how do I get this published my my local maven repo?

**Comment by AlfySoftware** [comment]
> 我创建了一个添加新功能的分支@AlfySoftware @cooltheo，查看：[https ://github.com/Eduardo-T/openai-java-20240614](https://github.com/Eduardo-T/openai-java-20240614)

I also created a new branch of functionality based on the library, 
the project is at https://gitee.com/alfy-software/openai-java-sdk,

### function_call usage 
 
```java 
final List<ChatMessage> messagesByCallback = new ArrayList<>(); 
final ChatMessage userMessage = new ChatMessage(ChatMessageRole.USER.value(), "What is the weather like in Boston?"); 
messagesByCallback.add(userMessage); 
 
 
final List<CallbackFunction> functions = new LinkedList<>(); 
 
String parmJson = "{\"type\":\"object\",\"properties\":{\"location\":{\"type\":\"string\",\"description\":\"The city and state, e.g. San Francisco, CA\"},\"unit\":{\"type\":\"string\",\"enum\":[\"celsius\",\"fahrenheit\"]}},\"required\":[\"location\"]}"; 
final CallbackFunction callbackFunction = new CallbackFunction("get_current_weather", "Get the current weather in a given location", parmJson); 
functions.add(callbackFunction); 
 
 
ChatCompletionRequest chatCompletionRequestByCallback = ChatCompletionRequest 
.builder() 
.model("gpt-3.5-turbo-16k") 
.functions(functions) 
.messages(messagesByCallback) 
.n(1) 
.maxTokens(50) 
.logitBias(new HashMap<>()) 
.build(); 
 
service.createChatCompletion(chatCompletionRequestByCallback).getChoices().forEach(System.out::println); 
```

**Comment by AlfySoftware** [comment]
I also created a new branch of functionality based on the library,
the project is at https://gitee.com/alfy-software/openai-java-sdk,

### function_call usage

```java
final List<ChatMessage> messagesByCallback = new ArrayList<>();
final ChatMessage userMessage = new
ChatMessage(ChatMessageRole.USER.value(), "What is the weather like in
Boston?");
messagesByCallback.add(userMessage);


final List<CallbackFunction> functions = new LinkedList<>();

String parmJson =
"{\"type\":\"object\",\"properties\":{\"location\":{\"type\":\"string\",\"description\":\"The
city and state, e.g. San Francisco,
CA\"},\"unit\":{\"type\":\"string\",\"enum\":[\"celsius\",\"fahrenheit\"]}},\"required\":[\"location\"]}";

final CallbackFunction callbackFunction = new
CallbackFunction("get_current_weather", "Get the current weather in a given
location", parmJson);
functions.add(callbackFunction);


ChatCompletionRequest chatCompletionRequestByCallback =
ChatCompletionRequest
.builder()
.model("gpt-3.5-turbo-16k")
.functions(functions)
.messages(messagesByCallback)
.n(1)
.maxTokens(50)
.logitBias(new HashMap<>())
.build();

service.createChatCompletion(chatCompletionRequestByCallback).getChoices().forEach(System.out::println);

```


Best regards!
------------------------------
Alfy
T: +1 2602275048 | P: +86 18107529335


davidb-e4s ***@***.***> 于2023年6月19日周一 13:47写道：

**Comment by AlfySoftware** [comment]
## Maven Importing
```xml
   <dependency>
    <groupId>cn.ai-connect</groupId>
    <artifactId>openai-java-sdk</artifactId>
    <version>1.0.0</version>
   </dependency>
```


Best regards!
------------------------------
Alfy
T: +1 2602275048 | P: +86 18107529335


davidb-e4s ***@***.***> 于2023年6月19日周一 13:47写道：
