### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by bjs250** [TheoKanning/openai-java#3]
In the readme, the following link 404's: https://github.com/TheoKanning/openai-java/blob/main/client/src/main/java/openai/OpenAiApi.java

I believe it should instead link to: https://github.com/TheoKanning/openai-java/blob/main/client/src/main/java/com/theokanning/openai/OpenAiService.java

**Comment by TheoKanning** [comment]
Fixed in cdfceb0

Thanks for pointing this out!
