### ISSUE TITLE
Conflicting package names when importing from Maven

### ISSUE THREAD

**Issue by LBurston** [TheoKanning/openai-java#30]
When only using Maven, not Gradle, api and client both use com.theokanning.openai as the package name, and so maven cannot build as the error `module [X] reads package com.theokanning.openai from both client and api`. Unless there is no way to use without Gradle?

**Comment by TheoKanning** [comment]
Does this still happen even if you only import the client package? I've never used maven so I can't help much.

I'll do some research about this, maybe I'll have to change the package names when I get to version 1.0

**Comment by yeikel** [comment]
I am using Maven, and I did not see this issue importing only the client
