### ISSUE TITLE
I am using the gpt3.5 model, but the answer is still the gpt3 model?

### ISSUE THREAD

**Issue by toywl** [TheoKanning/openai-java#309]
![image](https://github.com/TheoKanning/openai-java/assets/94053521/84a35054-0b28-49be-8881-4802e40b198a)

**Comment by toywl** [comment]
Okay, I understand
![image](https://github.com/TheoKanning/openai-java/assets/94053521/1d5eb674-47c0-4e12-a37b-06dcb7517ee5)

**Comment by xia2206636330** [comment]
我也发现了这个问题，修改mode没有用，一直是3.5的模型，请问您解决了吗？
