### ISSUE TITLE
import using maven fails

### ISSUE THREAD

**Issue by JanCantCode** [TheoKanning/openai-java#327]
I am trying to install this library in a maven repository, but when trying to reload dependencies, it fails. I have used the "official" import from the readme: ```<dependency>
            <groupId>com.theokanning.openai-gpt3-java</groupId>
            <artifactId>service</artifactId>
            <version>version</version>
        </dependency>``` this tho, results me in ```[com.theokanning.openai-gpt3-java:service:jar:version was not found in https://repo.maven.apache.org/maven2 during a previous attempt.)```

**Comment by AndrewHogg** [comment]
Version would have to be a released version, current version at the time of writing is 0.14.0 - I've got in my pom.xml


```
<dependency>
	<groupId>com.theokanning.openai-gpt3-java</groupId>
	<artifactId>api</artifactId>
	<version>0.14.0</version>
</dependency>
<dependency>
	<groupId>com.theokanning.openai-gpt3-java</groupId>
	<artifactId>service</artifactId>
	<version>0.14.0</version>
</dependency>
<dependency>
	<groupId>com.theokanning.openai-gpt3-java</groupId>
	<artifactId>client</artifactId>
	<version>0.14.0</version>
</dependency>
```

**Comment by JanCantCode** [comment]
yeah i just figured that out after looking at the maven repo.. i tried it with 1.0.0 after, which obviously also failed xD 

thanks for the help tho

**Comment by TanayMorakhia** [comment]
@AndrewHogg I think it would be better if you could mention it in the documentation because I also fell for it the first time.
