### ISSUE TITLE
File object is missing status and status_details fields

### ISSUE THREAD

**Issue by patc888** [TheoKanning/openai-java#355]

**Comment by patc888** [comment]
It seems these fields are missing from the File java object.

status
string
The current status of the file, which can be either uploaded, processed, pending, error, deleting or deleted.

status_details
string or null
Additional details about the status of the file. If the file is in the error state, this will include a message describing the error.

**Comment by gonglb** [comment]
I also encountered the same problem, without status, I don't know when to create a 3.5 fine-tuning task

**Comment by mcheung610** [comment]
I also encountered the same issue.

**Comment by TheoKanning** [comment]
This will be in the next release 👍
