### ISSUE TITLE
No Retrieve file content api

### ISSUE THREAD

**Issue by gaoxt1983** [TheoKanning/openai-java#366]
I can not find the api which retrieve the file content, is it missing?

**Comment by costescuandrei** [comment]
Same here. Maybe we should provide a pull request...

**Comment by costescuandrei** [comment]
I added the missing retrieveFileContent method.
Please review and merge https://github.com/TheoKanning/openai-java/pull/367 if it's ok.

Cheers!

**Comment by TheoKanning** [comment]
This is fixed in `0.16.1` 👍
