### ISSUE TITLE
Support DALL-E 3

### ISSUE THREAD

**Issue by cjmalloy** [TheoKanning/openai-java#387]
DALL-E 3 is now available: https://openai.com/blog/dall-e-3-is-now-available-in-chatgpt-plus-and-enterprise

Need to add 'model' option to CreateImageRequest and set it to "dall-e-3".

In the meanwhile, is there an easy way to add custom fields to a request?

**Comment by cjmalloy** [comment]
Nevermind, forgot to search PRs: https://github.com/TheoKanning/openai-java/pull/386

**Comment by minji1289** [comment]
I also wish the PR to be approved #386 so that I can use updated version of the dall-e-3 model!

**Comment by TheoKanning** [comment]
This is fixed in https://github.com/TheoKanning/openai-java/pull/393, I'll deploy a new version soon :+1:

**Comment by TheoKanning** [comment]
This is included in 0.17.0 🎉
