### ISSUE TITLE
suggest support a NoArgsConstructor for ChatFunction

### ISSUE THREAD

**Issue by Jack-Cui** [TheoKanning/openai-java#389]
com.theokanning.openai.completion.chat.ChatFunction has no NoArgsConstructor, Causes deserialization to fail。when I use spring find this problem, report an error as follows:
reason is: JSON parse error: Cannot construct instance of `com.theokanning.openai.completion.chat.ChatFunction` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.theokanning.openai.completion.chat.ChatFunction` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)\n at [Source: (PushbackInputStream); line: 10, column: 10] (through reference chain: com.jy.business.common.bo.ChatRequest[\"functions\"]->java.util.ArrayList[0])
so suggest support  a NoArgsConstructor for ChatFunction like ChatMessage

**Comment by TheoKanning** [comment]
Fixed in the latest release :+1:
