### ISSUE TITLE
Add support for assistants

### ISSUE THREAD

**Issue by robinwithes** [TheoKanning/openai-java#390]
https://platform.openai.com/assistants

**Comment by propertius** [comment]
Interest here as well :)

**Comment by bjorkman** [comment]
Me too!

**Comment by remyohajinwa** [comment]
Working on this now

**Comment by mrlobotomy** [comment]
I'm working on it too ;)

**Comment by remyohajinwa** [comment]
@mrlobotomy I already started working on this. Can you pick another issue please ?

**Comment by remyohajinwa** [comment]
Just so we don't spend a lot of time doing the same work

**Comment by mrlobotomy** [comment]
No worries- any idea how long you'll be? I've made the changes locally and am just creating tests but am happy to just use it myself until you're finished.

**Comment by remyohajinwa** [comment]
@mrlobotomy have you implemented all the endpoints. Maybe you can push, and we can compare what we have. I'm also writing tests. You can reach me on remyoha@gmail.com so that we can look at it together

**Comment by mrlobotomy** [comment]
You can see a clone of the repo on my profile - with my wip

**Comment by remyohajinwa** [comment]
Good work! @mrlobotomy it seems you have really gone far with Assistants, Threads, Messages and Runs. I have worked on Assistants. is there a way we can merge so that you have mine (Assistants) and yours (Threads, Messages and Runs) ?

**Comment by bjorkman** [comment]
Haha I did too -  almost done, but happy to use use your code instead. Maybe we should notify each other when we start implementing things? I will use mine until yours are merged, Theos excellent framework makes me think it will be just changing a few method names and then go, the principle is clear! :)

**Comment by TheoKanning** [comment]
This is included in 0.17.0 :tada:

**Comment by bjorkman** [comment]
Hm the assistants part is done, but not anything with using them - I think maybe this was closed a bit prematurely. I've done most of the other parts, will try to fix the last stuff today and make a PR

**Comment by vacuityv** [comment]
I don't think it's done. Where is thread and run part? The only thing I can do with it now is careate assistant and file. And nothing else. WTF

**Comment by bjorkman** [comment]
I've been working on the other parts, but unfortunately I got sick today - maybe I can have something ready on wednesday if no one else has already started

**Comment by vacuityv** [comment]
Sorry to hear that. Take care of yourself. Maybe you guys should merge each other first and then push pr.Anyway thanks for all of yours. 在 2023年11月14日，00:31，Peter Björkman ***@***.***> 写道：﻿
I've been working on the other parts, but unfortunately I got sick today - maybe I can have something ready on wednesday if no one else has already started

**Comment by TheoKanning** [comment]
Sorry for the confusion here, I have some time tonight and I'll see how far I can get on this

**Comment by vacuityv** [comment]
@TheoKanning I also have some time available, and there are a few parts that still need to be completed: threads, messages, and runs. Could you please assign the tasks and allocate some to me as well, to avoid wasting time by developing the same parts separately? The tool in the assistants section also needs some modifications. When the type is “function,” parameters need to be added.

**Comment by TheoKanning** [comment]
@vacuityv I just added Messages and one method (create) for Threads https://github.com/TheoKanning/openai-java/commit/037606eeb1b753e15725db00f3c397cfe7c19090

I also fixed Tool issue and your builder issue.

Could you finish Threads? I'm done for now so go ahead and do Runs if you have time

**Comment by vacuityv** [comment]
@TheoKanning  OK. I will finish Threads and Runs.

**Comment by vacuityv** [comment]
@TheoKanning  I misunderstand your message. I will finish Threads.

**Comment by vacuityv** [comment]
@TheoKanning  I added a pr. If there is any issure in the pr, let me know and I will fix ASAP. Thanks for all of this.

**Comment by remyohajinwa** [comment]
Sorry about the confusion and the hassle guys. I'm glad we were able to get on it

**Comment by bjorkman** [comment]
Just made a PR for runs, so if the outstanding branches are merged I think we are feature complete?

**Comment by vacuityv** [comment]
@bjorkman  Your pr didn't pass the auto check. @TheoKanning Sorry to disturb you. When will this part finish. I can do some job if you don't have enough time for that. I want to do something to my own website so I need it. I'm sorry if this offends you.

**Comment by bjorkman** [comment]
Ah JDk 1.8... I'll fix the offending line and make a new PR!

**Comment by bjorkman** [comment]
Done!

**Comment by TheoKanning** [comment]
Just merged your Run code and released version 0.18.0!

Thank you so much! I appreciate all of the help when OpenAI drops a bunch of new features all at once like this

**Comment by vacuityv** [comment]
@TheoKanning  sorry to disturb you again. I just met a issure here : https://github.com/TheoKanning/openai-java/issues/407

**Comment by vacuityv** [comment]
@bjorkman hello man. Where is the required_action object in Run ? And "last_error" shoube be a object not a string ? Can you guys be careful because there is real person use this sdk. Please check again carefully. If you don't have time for it just let me know and I will do.

**Comment by vacuityv** [comment]
@TheoKanning  Can you give me higher permissions for this repository? This way, I can help you with some simple tasks, such as code review. I think it’s necessary to check it a bit, as I’ve encountered many issues while integrating with the assistant. Additionally, with a 14-hour time difference, this can ensure that the project is updated more promptly.

**Comment by remyohajinwa** [comment]
@vacuityv I agree that maybe more people should have some permission so that we can be fast in fixing issues

**Comment by remyohajinwa** [comment]
@vacuityv what issues are you facing currently with Assistants

**Comment by vacuityv** [comment]
> @bjorkman hello man. Where is the required_action object in Run ? And "last_error" shoube be a object not a string ? Can you guys be careful because there is real person use this sdk. Please check again carefully. If you don't have time for it just let me know and I will do.

@remyohajinwa  this.

**Comment by vacuityv** [comment]
@remyohajinwa  and also when create assistant, the function is different from the chat function.

**Comment by vacuityv** [comment]
@remyohajinwa @TheoKanning  and I think there is also an error in MessageContent:

```
public class MessageContent {
    String type;
    Text text;
    @JsonProperty("image_file")
    ImageFile imageFile;
}
```

But in openai documen is : The content of the message in array of text and/or images.

So I think there is no "type" in MessageContent, and should have "type" in "Text" and "ImageFile"

**Comment by remyohajinwa** [comment]
@vacuityv I think it's the same function but maybe the way it was put in the class was not the proper way but the function in the documentation is the same as **ChatFunction** class.  We just have to make sure we are using it the proper way. E.g I believe the right way should be to have Three classes (CodeInterpreter, Function, Retrieval) extending a Parent class.

then the Function class would have the parameters
private String type;
private ChatFunction function.

I believe that's the contract on the API

**Comment by remyohajinwa** [comment]
@vacuityv I agree with you that we should be resolving these issues ASAP. Maybe we'll wait for @TheoKanning to give direction

**Comment by remyohajinwa** [comment]
Also maybe we should have a group (maybe slack) so that everyone is informed on issues being worked on. This will help in tracking issues

**Comment by vacuityv** [comment]
@remyohajinwa  I don't think they are the same function. In chat part the code can auto excute the function. But in assistant part you need excute it when they require and send the function result to the assistant. They have different excute ways.

**Comment by bjorkman** [comment]
@vacuityv Please feel free to improve it if you feel that something isn't working right - of course no code is perfect the first check-in, so we find errors and then fix them - that's the beauty of programming! :)

**Comment by vacuityv** [comment]
I will fix what I found. Except the function.
