### ISSUE TITLE
OpenAiHttpException: Invalid URL (POST /v1/audio/speech) on createSpeech

### ISSUE THREAD

**Issue by aderaynal** [TheoKanning/openai-java#425]
I updated to version 0.18.2 and I try to run this code

```
OpenAiService service = new OpenAiService(MY_KEY, Duration.ofSeconds(120));
CreateSpeechRequest csr = CreateSpeechRequest.builder().input(text).model("gpt-4").voice("echo").build();
ResponseBody resp = service.createSpeech(csr);
```

but the last line throws an OpenAiHttpException with this message: `Invalid URL (POST /v1/audio/speech)`

**Comment by Aelentel** [comment]
@aderaynal hello, you may want to read the model documentation for the text to speech api.

valid model identifier are :
- tts-1
- tts-1-hd

**Comment by aderaynal** [comment]
it worked.
RTFM ;-)

Thank you very much for responding and maintaining this library.
