### ISSUE TITLE
In the example, there is confusion about whether each message sent includes all previous messages in the context.

### ISSUE THREAD

**Issue by Xxm-YX** [TheoKanning/openai-java#458]
Could you please clarify whether it is necessary to send the entire message history along with each new message when communicating with ChatGPT?

**Comment by JoyerLiu** [comment]
The OpenAI aspect does not store any information about the context you previously transmitted. Whether to transmit historical messages depends on whether you need ChatGPT to understand the context and provide new answers based on context. If AI does not need to understand the context, historical messages can be excluded. This question should have a relevant explanation in the OpenAI API.

**Comment by Xxm-YX** [comment]
Thanks！
