### ISSUE TITLE
retrofit2 429 exception

### ISSUE THREAD

**Issue by parisana** [TheoKanning/openai-java#46]
Facing the below error
`java.util.concurrent.CompletionException: retrofit2.adapter.rxjava2.HttpException: HTTP 429`
Details:
- I have 7 threads creating a new instance of the OpenAiService.
- I have quite a few requests made on each thread.
- What is the cause of this exception. I know I have not exceeded my rate limit.

**Comment by pepitoscrespo** [comment]
Use another user. That works for me.

**Comment by TheoKanning** [comment]
Try upgrading to 0.10.0 and using the `OpenAiService` from the new `service` library. It will read the server error message and display it in the stack trace for you.
