### ISSUE TITLE
Always getting only one CompletionChoice object as a responce.

### ISSUE THREAD

**Issue by R4Di04CTiV3** [TheoKanning/openai-java#48]
I'm facing an issue where always is only returned a single `CompletionChoice` object in response to a `CompletionRequest` and not the full list of `CompletionChoice` objects. Any ideas why is this happening?

**Comment by TheoKanning** [comment]
@R4Di04CTiV3 are you still seeing this issue? I added the `n` parameter to CompletionTest and it appears to be working.

https://github.com/TheoKanning/openai-java/pull/61

**Comment by R4Di04CTiV3** [comment]
@TheoKanning it's working as expected now, thanks!

**Comment by TheoKanning** [comment]
Great!
