### ISSUE TITLE
Continue completion response

### ISSUE THREAD

**Issue by ffritsche** [TheoKanning/openai-java#49]
Is there a way to continue a completion response if the reason is length?
I get a 
```
 java.net.SocketTimeoutException: timeout
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:90)
	at io.reactivex.Single.blockingGet(Single.java:2002)
	at com.theokanning.openai.OpenAiService.createCompletion(OpenAiService.java:91)
```
when I set maxTokens>500

**Comment by ferreirarod** [comment]
Have you tried passing a timeout parameter when creating the service?
`var service = new OpenAiService(apiToken, API_SOCKET_TIMEOUT);`

**Comment by TheoKanning** [comment]
@ffritsche I think ferreirarod has the right solution here, have you tried increasing the timeout to 30 seconds?

**Comment by ffritsche** [comment]
Hey thanks that helps.
But is there a way to continue the results like in the playground?

**Comment by kazihar** [comment]
> Have you tried to provide a timeout parameter when creating the service?
> 
> `var service = new OpenAiService(apiToken, API_SOCKET_TIMEOUT);`

OpenAiService constructor doesn't allow two  arguments, it allows apiToken only, how can i tweak it?

**Comment by shanali10** [comment]
It does allow two arguments token and timeout

**Comment by TheoKanning** [comment]
Moving this to https://github.com/TheoKanning/openai-java/issues/75
