### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by WirelessMind** [TheoKanning/openai-java#62]
I can't use this library on my software because I get this error:

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/home/admin/test.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

I use the client.
`OpenAiService service = new OpenAiService(token, API_SOCKET_TIMEOUT);`

Any solution?

Thanks

**Comment by BenTrotter** [comment]
I have hit the same issue
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform`

**Comment by zKarp** [comment]
@WirelessMind & @BenTrotter I had to downgrade retrofit to b/c I was using Java 11. 
Added this to my build.gradle `implementation("com.squareup.retrofit2:retrofit:2.7.2")`

**Comment by WirelessMind** [comment]
Thank you!
It works!!!
