### ISSUE TITLE
Override base url and header with gateway data

### ISSUE THREAD

**Issue by vincentklg** [TheoKanning/openai-java#81]
So in my company we use an api gateway (Gravitee) to provide a central point for all apis (internal and external).
We use our own api key internally and let the gateway transform the headers.

Question 1: How can we change the base url to our gateway?
Question 2: How can we use different headers for all requests?

All help is greatly appreciated :)

**Comment by TheoKanning** [comment]
You'll have to make your own instance of `OpenAiApi` and pass it to the `OpenAiService` constructor. I added a section to the readme about how customize everything https://github.com/TheoKanning/openai-java#customizing-openaiservice.

For example to set the base url:
```
Retrofit retrofit = defaultRetrofit(client, mapper)
        .newBuilder()
        .baseUrl(YOUR_URL)
        .build()
````

Not sure how to make separate headers for each request off the top of my head, but you should be able to customize anything you want now.
