### ISSUE TITLE
Exception:  AuthenticationInterceptor cannot be cast to class okhttp3.Interceptor

### ISSUE THREAD

**Issue by xsfang** [TheoKanning/openai-java#94]
While I try to run the OpenAiApiExample.java, or to run my own java codes to use this java API. I got an exception. 

AuthenticationInterceptor cannot be cast to class okhttp3.Interceptor

In the class OpenAiService.java, there is a line:

       OkHttpClient client = new OkHttpClient.Builder().addNetworkInterceptor(new AuthenticationInterceptor(token)).connectionPool.........

Please take a look. Thank you.

**Comment by xsfang** [comment]
Solved.

**Comment by PeterBrownie** [comment]
What was your solution for this? I seem to be getting a "Caused by: java.lang.NoClassDefFoundError: okhttp3/Interceptor". Maybe my issue is somewhat related?
